; Compile with Inno Setup 6.2 or newer via Build-Installer.ps1.
#ifndef PublishDir
  #error PublishDir must point to a fresh self-contained win-x64 publish directory.
#endif
#ifndef AppVersion
  #define AppVersion "1.0.0"
#endif

[Setup]
AppId={{E3C50EBF-1637-4288-B573-C73CE62BCF2F}
AppName=AudioZen
AppVersion={#AppVersion}
AppPublisher=AudioZen
DefaultDirName={localappdata}\Programs\AudioZen
DisableDirPage=yes
DefaultGroupName=AudioZen
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
MinVersion=10.0.17763
WizardStyle=modern
LicenseFile=..\LICENSE
SetupIconFile=..\AudioUI\icon.ico
UninstallDisplayIcon={app}\AudioUI.exe
OutputDir=..\artifacts\installer
OutputBaseFilename=AudioZen.Setup
Compression=lzma2
SolidCompression=yes
SetupLogging=yes
CloseApplications=yes
RestartApplications=no
SetupMutex=AudioZenSetup

[Tasks]
Name: "melda"; Description: "Melda MCompressor / MCharmVerb（壓縮與殘響，選用）"; GroupDescription: "連網安裝的選用元件："
Name: "speech"; Description: "繁體中文（台灣）語音辨識（喚醒詞，選用）"; GroupDescription: "連網安裝的選用元件："

[Files]
Source: "Install-Dependencies.ps1"; Flags: dontcopy
Source: "dependencies.json"; Flags: dontcopy
Source: "..\AudioUI\appsettings.example.json"; Flags: dontcopy
Source: "{#PublishDir}\*"; DestDir: "{app}"; Excludes: "appsettings.json,config\*,*.pdb"; Flags: ignoreversion recursesubdirs createallsubdirs
; Only sanitized defaults generated by the prerequisite step may enter a new installation.
Source: "{tmp}\dependency-result.settings.json"; DestDir: "{app}"; DestName: "appsettings.json"; Flags: external onlyifdoesntexist uninsneveruninstall

[Icons]
Name: "{userprograms}\AudioZen"; Filename: "{app}\AudioUI.exe"; WorkingDir: "{app}"

[Run]
Filename: "{app}\AudioUI.exe"; Description: "開啟 AudioZen"; WorkingDir: "{app}"; Flags: postinstall nowait skipifsilent runasoriginaluser

[Messages]
ButtonNext=下一步(&N) >
ButtonBack=< 上一步(&B)
ButtonCancel=取消
ButtonInstall=安裝(&I)
ButtonFinish=完成(&F)
SelectTasksLabel2=Equalizer APO、Voicemeeter Banana 與 VB-CABLE 為必要項目，已安裝者會略過。下列選用項目預設勾選，可取消。

[Code]
#include "ResumeCopy.iss"

const
  ResumeKey = 'Software\Microsoft\Windows\CurrentVersion\RunOnce';
  ResumeName = 'AudioZen Setup';

function InitializeSetup: Boolean;
begin
  Result := not WizardSilent;
  if not Result then
    MsgBox('此安裝程式需要互動確認第三方授權與裝置，請以一般方式開啟。', mbError, MB_OK);
end;

function UpdateReadyMemo(Space, NewLine, MemoUserInfoInfo, MemoDirInfo,
  MemoTypeInfo, MemoComponentsInfo, MemoGroupInfo, MemoTasksInfo: String): String;
begin
  Result := MemoDirInfo + NewLine + MemoTasksInfo + NewLine + NewLine +
    'AudioZen 已內含 .NET Runtime。缺少的系統元件會從官方來源下載並驗證。' + NewLine +
    '安裝系統元件時會要求管理員授權；請在各安裝畫面確認授權與裝置選項。' + NewLine +
    '若第三方詢問重開機，請先選「稍後」。AudioZen Setup 會提示重開機，登入後繼續。' + NewLine +
    '安裝完成後，首次設定仍需填入 Gemini API key、選擇實體耳機／喇叭並確認路由。';
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ExitCode, Line: Integer;
  Parameters, CacheDirectory, CachedSetup, ReportPath, SourceSetup, SetupHash: String;
  ErrorLines: TArrayOfString;
begin
  Result := '';
  CacheDirectory := ExpandConstant('{localappdata}\AudioZen\Setup');
  SourceSetup := ExpandConstant('{srcexe}');
  ReportPath := ExpandConstant('{tmp}\dependency-result');
  // Never overwrite a previous executable: it may still be open or protected.
  // Content identity also separates different builds with the same AppVersion.
  try
    SetupHash := GetSHA256OfFile(SourceSetup);
    CachedSetup := CacheDirectory + '\' + SetupHash + '\AudioZen.Setup.exe';
    if not ForceDirectories(ExtractFileDir(CachedSetup)) then begin
      Result := '無法建立安裝續接目錄：' + ExtractFileDir(CachedSetup);
      Exit;
    end;
    if FileExists(CachedSetup) then begin
      if CompareText(GetSHA256OfFile(CachedSetup), SetupHash) <> 0 then begin
        Result := '安裝續接副本驗證失敗，請刪除該副本後重試：' + CachedSetup;
        Exit;
      end;
      Log('Reusing verified resume installer: ' + CachedSetup);
    end else begin
      Log('Caching resume installer from ' + SourceSetup + ' to ' + CachedSetup);
      Result := CopyResumeInstaller(SourceSetup, CachedSetup);
      if Result <> '' then Exit;
      if CompareText(GetSHA256OfFile(CachedSetup), SetupHash) <> 0 then begin
        DeleteFile(CachedSetup);
        Result := '安裝續接副本複製後驗證失敗，請重試。';
        Exit;
      end;
    end;
  except
    Result := '無法準備安裝續接副本：' + GetExceptionMessage;
    Exit;
  end;

  // Register before invoking a vendor: it may reboot directly. Always resume as the original user.
  if not RegWriteStringValue(HKCU, ResumeKey, ResumeName,
    '"' + CachedSetup + '" /TASKS="' + WizardSelectedTasks(False) + '"') then begin
    Result := '無法登記重新登入後繼續安裝。';
    Exit;
  end;
  ExtractTemporaryFile('Install-Dependencies.ps1');
  ExtractTemporaryFile('dependencies.json');
  ExtractTemporaryFile('appsettings.example.json');
  Parameters := '-NoProfile -ExecutionPolicy Bypass -File "' +
    ExpandConstant('{tmp}\Install-Dependencies.ps1') + '" -AppDirectory "' +
    ExpandConstant('{app}') + '" -ReportPath "' + ReportPath + '"';
  if WizardIsTaskSelected('melda') then Parameters := Parameters + ' -IncludeMelda';
  if WizardIsTaskSelected('speech') then Parameters := Parameters + ' -IncludeSpeech';

  if not ShellExec('runas', ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'),
    Parameters, '', SW_SHOWNORMAL, ewWaitUntilTerminated, ExitCode) then begin
    RegDeleteValue(HKCU, ResumeKey, ResumeName);
    Result := '未取得管理員授權或無法啟動相依安裝，尚未安裝 AudioZen。請重試。' + #13#10 +
      SysErrorMessage(ExitCode);
    Exit;
  end;
  FileCopy(ReportPath + '.log', CacheDirectory + '\dependencies.log', False);
  if ExitCode = 3010 then begin
    NeedsRestart := True;
    Result := '系統元件需要重新啟動 Windows。請儲存工作後重新開機；再次登入此帳號時會繼續安裝。' + #13#10 +
      '若未自動繼續，可重新執行：' + CachedSetup;
    Exit;
  end;
  RegDeleteValue(HKCU, ResumeKey, ResumeName);
  if ExitCode <> 0 then begin
    Result := '相依安裝尚未完成。請重試；選用元件可返回上一頁取消勾選。' + #13#10 +
      '記錄：' + CacheDirectory + '\dependencies.log';
    if LoadStringsFromFile(ReportPath, ErrorLines) then
      for Line := 0 to GetArrayLength(ErrorLines) - 1 do
        Result := Result + #13#10 + ErrorLines[Line];
  end;
end;
